image: alpine/latest
packages:
  - rustup
triggers:
  - action: email
    condition: failure
    to: Aiden Langley <aiden@nedia.dev>
tasks:
  - rustup: |
      rustup-init -y
      echo "source $HOME/.cargo/env" >> .buildenv
  - setup: |
      rustup toolchain install nightly stable
      cd nedots.rs
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd nedots.rs
      cargo build --verbose
      cargo test --lib --verbose
  - nightly: |
      rustup default nightly
      cd nedots.rs
      cargo build --verbose ||:
      cargo test --lib --verbose ||:
  - docs: |
      cd nedots.rs
      rustup run stable cargo doc --no-deps
      rustup run nightly cargo doc --no-deps ||:
