image: alpine/latest
packages:
  - rustup
triggers:
  - action: email
    condition: failure
    to: Aiden Langley <aiden@nedia.dev>
secrets:
  - f049bb15-5272-485e-b7ca-67b90598d980
environment:
  known_hosts: |
    git.sr.ht ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZvRd4EtM7R+IHVMWmDkVU3VLQTSwQDSAvW0t2Tkj60
    git.sr.ht ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCj6y+cJlqK3BHZRLZuM+KP2zGPrh4H66DacfliU1E2DHAd1GGwF4g1jwu3L8gOZUTIvUptqWTkmglpYhFp4Iy4=
  remote: git@git.sr.ht:~nedia/nedots
  nedots: nedots.rs/target/debug/nedots
  verbose: $nedots -vvvv
tasks:
  - rustup: |
      rustup-init -y
      echo "source $HOME/.cargo/env" >> .buildenv
  - setup: |
      rustup toolchain install stable
      cd nedots.rs
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd nedots.rs
      cargo build
      chmod +x target/debug/nedots
  - init: |
      echo $known_hosts >> .ssh/known_hosts
      ./$verbose init --from-user aiden $remote
  - install: |
      ./$verbose install
      # ./$verbose install # Intentionally installing twice
  - backup: ./$verbose backup
  - clean: ./$verbose clean --dots --backups --assumeyes
  - sync: ./$verbose sync --gather --nopush
  - user_friendly: |
      $nedots install
      $nedots backup
      $nedots clean -dby
      $nedots sync -gn
