image: alpine/latest
packages:
  - rustup
triggers:
  - action: email
    condition: failure
    to: Aiden Langley <aiden@nedia.dev>
tasks:
  - rustup: |
      rustup-init -y
      echo "source $HOME/.cargo/env" >> .buildenv
  - setup: |
      rustup toolchain install stable
      cd nedots.rs
      rustup run stable cargo fetch
  - test: |
      rustup default stable
      cd nedots.rs
      cargo test --lib --verbose
  - docs: |
      cd nedots.rs
      rustup run stable cargo doc --no-deps
